---
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  # Handy for un-pairing/resetting BLE bonds on the host-connected (central) half
  - board: nice_nano_v2
    shield: settings_reset
